// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}/api/v1` | (string & {});
};

export type IdName = {
    id: number;
    name: string;
};

export type Campus = {
    id: number;
    name: string;
    city: [
        number | string,
        number | string
    ];
    latitude: number;
    longitude: number;
};

export type CampusMaster = {
    id: number;
    name: string;
    display_name: string;
    code: string;
    alias: string | false;
    city: [
        number | string,
        number | string
    ];
    area: Array<[
        string | number,
        string | number
    ]>;
    latitude: string | false;
    longitude: string | false;
    book_appointment: boolean;
    is_hospital: boolean;
    create_patient: boolean;
    enable_emergency: boolean;
};

export type Medium = {
    id: number;
    name: string;
};

export type Product = {
    id: number;
    name: string;
    type: string;
    lst_price: number;
    speciality_id: [
        number | string,
        number | string
    ] | false;
};

export type DoctorListResponse = {
    doctors: Array<Doctor>;
    total_count?: number;
    [key: string]: unknown;
};

export type Doctor = {
    id: number;
    name: string;
    speciality_id: [
        number | string,
        number | string
    ];
    image?: string;
    book_package: boolean;
    [key: string]: unknown;
};

export type Error = {
    error: string;
};

export type DoctorDetail = {
    id: number;
    name: string;
    display_name: string;
    speciality_id: [
        number | string,
        number | string
    ];
    book_appointments: boolean;
    active_doctor: boolean;
    doctor: boolean;
    city: string;
    image: string;
    [key: string]: unknown;
};

export type DoctorAvailabilityResponse = {
    availability: {
        [key: string]: {
            available: boolean;
        };
    };
    campuses: Array<{
        campus_id: number;
        name: string;
        city: string;
        sub_campus_id: number | false;
    }>;
};

export type TimeSlot = {
    id: number;
    start_datetime: string;
    stop_datetime: string;
    campus_id: [
        number | string,
        number | string
    ];
    sub_campus_id: [
        number | string,
        number | string
    ] | false;
    duration: number;
    consultation_type_ids: [
        number | string,
        number | string
    ];
};

export type SlotPrice = {
    price: number;
    slot_id?: number;
    currency?: string;
};

export type AppointmentDetail = {
    id: number;
    doctor: [
        number | string,
        number | string
    ];
    doctor_image_url: string;
    start_datetime: string;
    stop_datetime: string;
    speciality_id: [
        number | string,
        number | string
    ];
    consultation_type_ids: [
        number | string,
        number | string
    ];
    campus_id: number;
    sub_campus_id: number | false;
    product_id: [
        number | string,
        number | string
    ];
    availability: string;
    appointment_type: 'individual_appointment' | 'from_packaage';
    booked_package_name: number | false;
    virtual_consultation_url: string | false;
};

export type AppointmentDashboard = {
    upcoming_appointments: Array<{
        consultation_type: string;
        speciality: string;
        formatted_startdate: string;
        doctor_name: string;
        time: string;
        day?: string;
        name?: string;
    }>;
    completed_appointments: Array<{
        consultation_type: string;
        speciality: string;
        formatted_startdate: string;
        doctor_name: string;
        time: string;
        day?: string;
        name?: string;
    }>;
    next_appointment: {
        consultation_type: string;
        speciality: string;
        formatted_startdate: string;
        doctor_name: string;
        time: string;
        day?: string;
        name?: string;
    };
    total_appointment_counts: number;
};

export type BookAppointmentResult = {
    id: number;
    name: string;
    availability: string;
    appointment_type: string;
    consultation_type: string;
    consultation_type_id: [
        number | string,
        number | string
    ] | false;
    start_datetime: string;
    stop_datetime: string;
    duration: number;
    doctor_id: [
        number | string,
        number | string
    ] | false;
    lead_id: [
        number | string,
        number | string
    ] | false;
    campus_id: [
        number | string,
        number | string
    ] | false;
    sub_campus_id: [
        number | string,
        number | string
    ] | false;
    speciality_id: [
        number | string,
        number | string
    ] | false;
    slot_id: [
        number | string,
        number | string
    ] | false;
    caller_name: string;
    patient_name: string;
    payment_mode: string | false;
    amount: number;
    online_payment_url: string | false;
    virtual_consultation_url: string | false;
    zegocloud_uuid: string | false;
    booked_package_name: [
        number | string,
        number | string
    ] | false;
    product_id: [
        number | string,
        number | string
    ] | false;
    sale_id: [
        number | string,
        number | string
    ] | false;
    invoice_id: [
        number | string,
        number | string
    ] | false;
    invoice_count: number;
    create_date: string;
    write_date: string;
};

export type BookAppointmentData = {
    /**
     * Required for doctors, auto-resolved for patients
     */
    lead_id?: number;
    /**
     * 1=In-Person, 2=Virtual, 3=Home-Based
     */
    consultation_type_id: 1 | 2 | 3;
    campus_id: number;
    sub_campus_id?: number;
    appointment_type: 'individual_appointment' | 'from_packaage';
    availability: 'booked';
    caller_name: string;
    patient_name: string;
    payment_mode: 'cash' | 'online';
};

export type RescheduleAppointmentData = BookAppointmentData & {
    reschedule_slot_id: number;
};

export type CancelAppointmentResult = {
    message: string;
    sucess: boolean;
};

export type CancelAppointmentData = {
    medium_id: number;
    cancel_reason: string;
};

export type MediumItem = {
    id: number;
    name: string;
};

export type RoomIdResponse = {
    roomID: string;
};

export type UserDetails = {
    id: number;
    caller_mobile: string;
    partner_name: string;
    contact_name: string;
    caller_email: string;
};

export type Package = {
    id: number;
    package_name: string;
    amount_total: number;
    service_id: [
        number | string,
        number | string
    ];
    package_product_ids: Array<number>;
};

export type PackageProductLine = {
    id: number;
    product_id: [
        number | string,
        number | string
    ];
    sequence_no?: number;
    price_unit?: number;
    price_subtotal?: number;
    discount?: number;
};

export type ManagedPackage = {
    campus_id: [
        number | string,
        number | string
    ];
    lead_id: number;
    booked_package_id: number;
    package_stage: 'booked' | 'confirm' | 'in_progress' | 'done';
    package_id: [
        number | string,
        number | string
    ];
    package_cost: number;
    date: string;
    sequence_booking: boolean;
    caller_name: string;
    patient_name: string;
    lines: Array<BookedPackageProductLine>;
};

export type BookedPackageProductLine = {
    id: number;
    line_id?: number;
    product_id: [
        number | string,
        number | string
    ];
    sequence_no: number;
    price_subtotal: number;
    price_unit?: number;
    discount?: number;
    status: 'open' | 'scheduled' | 'done' | 'cancelled';
    speciality_id?: [
        number | string,
        number | string
    ];
};

export type BookPackageResult = {
    booking_id: number;
    message: string;
};

export type BookPackageData = {
    lead_id?: number;
    package_id: number;
    caller_name: string;
    patient_name: string;
    payment_mode: 'cash' | 'online';
    campus_id: number;
    sequence_booking: boolean;
    package_stage: 'booked';
    date?: string;
};

export type PaymentInitResponse = {
    jsonrpc: '2.0';
    id: unknown;
    result: {
        id: string;
        short_url: string;
        reference_id: string;
        status: string;
        amount: number;
        currency: string;
        description: string;
        customer: {
            name: string;
            email: string;
            contact: string;
        };
        accept_partial: boolean;
        expire_by: number;
        created_at: number;
        callback_url: string;
        callback_method: string;
        upi_link: boolean | string;
        whatsapp_link: boolean | string;
        reminder_enable: boolean;
        [key: string]: unknown;
    };
};

export type AppointmentPaymentParams = {
    /**
     * Auto-resolved for patients
     */
    lead_id?: number;
    /**
     * CRM lead UID
     */
    uid: string;
    slot_id: number;
    campus_id: number;
};

export type PackagePaymentParams = {
    /**
     * Auto-resolved for patients
     */
    lead_id?: number;
    booked_package_id: number;
    campus_id: number;
};

export type NotificationPreferences = {
    marketing: boolean;
    promotional: boolean;
    transactional: boolean;
    whatsapp: boolean;
};

export type Success = {
    success: boolean;
};

export type EnableNotificationData = {
    mobile: number;
    marketing: boolean;
    promotional: boolean;
    transactional: boolean;
    whatsapp: boolean;
};

export type PostAuthPatientSendOtpData = {
    body?: {
        phone: string;
        type?: 'login' | 'signup';
        email?: string;
    };
    path?: never;
    query?: never;
    url: '/auth/patient/send-otp';
};

export type PostAuthPatientSendOtpResponses = {
    /**
     * OTP sent successfully
     */
    200: {
        message: string;
        success: boolean;
    };
};

export type PostAuthPatientSendOtpResponse = PostAuthPatientSendOtpResponses[keyof PostAuthPatientSendOtpResponses];

export type PostAuthPatientVerifyLoginData = {
    body?: {
        phone: string;
        otp: string;
    };
    path?: never;
    query?: never;
    url: '/auth/patient/verify-login';
};

export type PostAuthPatientVerifyLoginErrors = {
    /**
     * Invalid OTP
     */
    401: unknown;
    /**
     * Patient not found in CRM
     */
    404: unknown;
};

export type PostAuthPatientVerifyLoginResponses = {
    /**
     * Login successful — includes accessToken and refreshToken
     */
    200: {
        message: string;
        success: boolean;
        /**
         * Short-lived JWT access token (RS256)
         */
        accessToken: string;
        /**
         * Long-lived refresh token
         */
        refreshToken: string;
        /**
         * Access token TTL in seconds
         */
        expiresIn: number;
    };
};

export type PostAuthPatientVerifyLoginResponse = PostAuthPatientVerifyLoginResponses[keyof PostAuthPatientVerifyLoginResponses];

export type PostAuthPatientSignupVerifyData = {
    body?: {
        phone: string;
        otp: string;
        firstName: string;
        lastName: string;
        email?: string;
        countryCode?: number;
        dob?: string;
    };
    path?: never;
    query?: never;
    url: '/auth/patient/signup/verify';
};

export type PostAuthPatientSignupVerifyErrors = {
    /**
     * Signup OTP verification failed
     */
    401: unknown;
};

export type PostAuthPatientSignupVerifyResponses = {
    /**
     * Signup successful — includes accessToken and refreshToken
     */
    200: {
        name: string;
        success: boolean;
        lead_id: number;
        /**
         * Short-lived JWT access token (RS256)
         */
        accessToken: string;
        /**
         * Long-lived refresh token
         */
        refreshToken: string;
        /**
         * Access token TTL in seconds
         */
        expiresIn: number;
    };
};

export type PostAuthPatientSignupVerifyResponse = PostAuthPatientSignupVerifyResponses[keyof PostAuthPatientSignupVerifyResponses];

export type PostAuthDoctorLoginData = {
    body?: {
        /**
         * One of: cadabams, whitefield, mysore, mindtalk
         */
        campus: string;
        email: string;
        password: string;
    };
    path?: never;
    query?: never;
    url: '/auth/doctor/login';
};

export type PostAuthDoctorLoginErrors = {
    /**
     * Invalid campus
     */
    400: unknown;
    /**
     * Invalid credentials
     */
    401: unknown;
};

export type PostAuthDoctorLoginResponses = {
    /**
     * Doctor login successful — includes accessToken and refreshToken
     */
    200: {
        hospitalDoctorId: number;
        crmDoctorId: number;
        employeeDoctorId: number;
        doctorRole: string;
        doctorName: string;
        campus: string;
        /**
         * Short-lived JWT access token (RS256)
         */
        accessToken: string;
        /**
         * Long-lived refresh token
         */
        refreshToken: string;
        /**
         * Access token TTL in seconds
         */
        expiresIn: number;
    };
};

export type PostAuthDoctorLoginResponse = PostAuthDoctorLoginResponses[keyof PostAuthDoctorLoginResponses];

export type PostAuthRefreshData = {
    body?: {
        refreshToken: string;
    };
    path?: never;
    query?: never;
    url: '/auth/refresh';
};

export type PostAuthRefreshErrors = {
    /**
     * Invalid or expired refresh token
     */
    401: unknown;
};

export type PostAuthRefreshResponses = {
    /**
     * New token pair (old refresh token is invalidated)
     */
    200: {
        /**
         * Short-lived JWT access token (RS256)
         */
        accessToken: string;
        /**
         * Long-lived refresh token
         */
        refreshToken: string;
        /**
         * Access token TTL in seconds
         */
        expiresIn: number;
    };
};

export type PostAuthRefreshResponse = PostAuthRefreshResponses[keyof PostAuthRefreshResponses];

export type PostAuthLogoutData = {
    body?: {
        refreshToken: string;
    };
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Invalid refresh token
     */
    401: unknown;
};

export type PostAuthLogoutResponses = {
    /**
     * Refresh token revoked
     */
    200: {
        success: boolean;
    };
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type GetMastersIllnessesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/masters/illnesses';
};

export type GetMastersIllnessesResponses = {
    /**
     * Success
     */
    200: Array<IdName>;
};

export type GetMastersIllnessesResponse = GetMastersIllnessesResponses[keyof GetMastersIllnessesResponses];

export type GetMastersServicesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/masters/services';
};

export type GetMastersServicesResponses = {
    /**
     * Success
     */
    200: Array<IdName>;
};

export type GetMastersServicesResponse = GetMastersServicesResponses[keyof GetMastersServicesResponses];

export type GetMastersRelationshipsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/masters/relationships';
};

export type GetMastersRelationshipsResponses = {
    /**
     * Success
     */
    200: Array<IdName>;
};

export type GetMastersRelationshipsResponse = GetMastersRelationshipsResponses[keyof GetMastersRelationshipsResponses];

export type GetMastersLocationsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/masters/locations';
};

export type GetMastersLocationsResponses = {
    /**
     * Success
     */
    200: Array<Campus>;
};

export type GetMastersLocationsResponse = GetMastersLocationsResponses[keyof GetMastersLocationsResponses];

export type GetMastersCampusesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/masters/campuses';
};

export type GetMastersCampusesResponses = {
    /**
     * Success
     */
    200: Array<CampusMaster>;
};

export type GetMastersCampusesResponse = GetMastersCampusesResponses[keyof GetMastersCampusesResponses];

export type GetMastersMediumsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/masters/mediums';
};

export type GetMastersMediumsResponses = {
    /**
     * Success
     */
    200: Array<Medium>;
};

export type GetMastersMediumsResponse = GetMastersMediumsResponses[keyof GetMastersMediumsResponses];

export type GetMastersProductsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/masters/products';
};

export type GetMastersProductsResponses = {
    /**
     * Success
     */
    200: Array<Product>;
};

export type GetMastersProductsResponse = GetMastersProductsResponses[keyof GetMastersProductsResponses];

export type GetDoctorsData = {
    body?: never;
    path?: never;
    query?: {
        speciality_id?: number;
        doctor_id?: number;
        start_datetime?: string;
        stop_datetime?: string;
        consultation_type_id?: number;
        consultation_type_ids?: number;
        campus_id?: string;
        sub_campus_id?: number;
        city?: string;
        area?: string;
        book_appointments?: 'true' | 'false';
    };
    url: '/doctors';
};

export type GetDoctorsErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetDoctorsError = GetDoctorsErrors[keyof GetDoctorsErrors];

export type GetDoctorsResponses = {
    /**
     * Filtered list of doctors
     */
    200: DoctorListResponse;
};

export type GetDoctorsResponse = GetDoctorsResponses[keyof GetDoctorsResponses];

export type GetDoctorsByIdData = {
    body?: never;
    path?: {
        id?: number;
    };
    query?: never;
    url: '/doctors/{id}';
};

export type GetDoctorsByIdErrors = {
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Not found
     */
    404: Error;
};

export type GetDoctorsByIdError = GetDoctorsByIdErrors[keyof GetDoctorsByIdErrors];

export type GetDoctorsByIdResponses = {
    /**
     * Doctor details
     */
    200: DoctorDetail;
};

export type GetDoctorsByIdResponse = GetDoctorsByIdResponses[keyof GetDoctorsByIdResponses];

export type GetDoctorsByIdInfoData = {
    body?: never;
    path?: {
        id?: number;
    };
    query?: {
        fields?: string;
    };
    url: '/doctors/{id}/info';
};

export type GetDoctorsByIdInfoErrors = {
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Not found
     */
    404: Error;
};

export type GetDoctorsByIdInfoError = GetDoctorsByIdInfoErrors[keyof GetDoctorsByIdInfoErrors];

export type GetDoctorsByIdInfoResponses = {
    /**
     * Full doctor info
     */
    200: Doctor;
};

export type GetDoctorsByIdInfoResponse = GetDoctorsByIdInfoResponses[keyof GetDoctorsByIdInfoResponses];

export type GetDoctorsByIdAvailabilityData = {
    body?: never;
    path?: {
        id?: number;
    };
    query?: {
        /**
         * ISO date string e.g. '2025-05-05'
         */
        start_datetime?: string;
        /**
         * ISO date string e.g. '2025-05-09'
         */
        stop_datetime?: string;
        /**
         * 1=In-Person, 2=Virtual
         */
        consultation_type_id?: number;
    };
    url: '/doctors/{id}/availability';
};

export type GetDoctorsByIdAvailabilityErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetDoctorsByIdAvailabilityError = GetDoctorsByIdAvailabilityErrors[keyof GetDoctorsByIdAvailabilityErrors];

export type GetDoctorsByIdAvailabilityResponses = {
    /**
     * Doctor listing with availability
     */
    200: DoctorAvailabilityResponse;
};

export type GetDoctorsByIdAvailabilityResponse = GetDoctorsByIdAvailabilityResponses[keyof GetDoctorsByIdAvailabilityResponses];

export type GetAppointmentsSlotsData = {
    body?: never;
    path?: never;
    query?: {
        doctor_id?: number;
        availability?: 'open' | 'booked';
        start_datetime?: string;
        stop_datetime?: string;
        consultation_type_ids?: number;
        campus_id?: number;
        sub_campus_id?: number;
    };
    url: '/appointments/slots';
};

export type GetAppointmentsSlotsErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetAppointmentsSlotsError = GetAppointmentsSlotsErrors[keyof GetAppointmentsSlotsErrors];

export type GetAppointmentsSlotsResponses = {
    /**
     * Available slots
     */
    200: Array<TimeSlot>;
};

export type GetAppointmentsSlotsResponse = GetAppointmentsSlotsResponses[keyof GetAppointmentsSlotsResponses];

export type GetAppointmentsSlotsBySlotIdPriceData = {
    body?: never;
    path?: {
        slotId?: number;
    };
    query?: never;
    url: '/appointments/slots/{slotId}/price';
};

export type GetAppointmentsSlotsBySlotIdPriceErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetAppointmentsSlotsBySlotIdPriceError = GetAppointmentsSlotsBySlotIdPriceErrors[keyof GetAppointmentsSlotsBySlotIdPriceErrors];

export type GetAppointmentsSlotsBySlotIdPriceResponses = {
    /**
     * Slot price
     */
    200: SlotPrice;
};

export type GetAppointmentsSlotsBySlotIdPriceResponse = GetAppointmentsSlotsBySlotIdPriceResponses[keyof GetAppointmentsSlotsBySlotIdPriceResponses];

export type GetAppointmentsData = {
    body?: never;
    path?: never;
    query: {
        start_datetime: string;
        /**
         * Required for doctors, auto-resolved for patients
         */
        lead_id?: number;
    };
    url: '/appointments';
};

export type GetAppointmentsErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetAppointmentsError = GetAppointmentsErrors[keyof GetAppointmentsErrors];

export type GetAppointmentsResponses = {
    /**
     * Appointments list
     */
    200: Array<AppointmentDetail>;
};

export type GetAppointmentsResponse = GetAppointmentsResponses[keyof GetAppointmentsResponses];

export type GetAppointmentsPreviousData = {
    body?: never;
    path?: never;
    query?: {
        lead_id?: number;
        package_product_id?: number;
    };
    url: '/appointments/previous';
};

export type GetAppointmentsPreviousErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetAppointmentsPreviousError = GetAppointmentsPreviousErrors[keyof GetAppointmentsPreviousErrors];

export type GetAppointmentsPreviousResponses = {
    /**
     * Previous appointments
     */
    200: Array<AppointmentDetail>;
};

export type GetAppointmentsPreviousResponse = GetAppointmentsPreviousResponses[keyof GetAppointmentsPreviousResponses];

export type GetAppointmentsDashboardData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Required for doctors, auto-resolved for patients
         */
        phone_number?: string;
    };
    url: '/appointments/dashboard';
};

export type GetAppointmentsDashboardErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetAppointmentsDashboardError = GetAppointmentsDashboardErrors[keyof GetAppointmentsDashboardErrors];

export type GetAppointmentsDashboardResponses = {
    /**
     * Dashboard data
     */
    200: AppointmentDashboard;
};

export type GetAppointmentsDashboardResponse = GetAppointmentsDashboardResponses[keyof GetAppointmentsDashboardResponses];

export type PutAppointmentsBookBySlotIdData = {
    body?: BookAppointmentData;
    path?: {
        slotId?: number;
    };
    query?: never;
    url: '/appointments/book/{slotId}';
};

export type PutAppointmentsBookBySlotIdErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type PutAppointmentsBookBySlotIdError = PutAppointmentsBookBySlotIdErrors[keyof PutAppointmentsBookBySlotIdErrors];

export type PutAppointmentsBookBySlotIdResponses = {
    /**
     * Booking result
     */
    200: BookAppointmentResult;
};

export type PutAppointmentsBookBySlotIdResponse = PutAppointmentsBookBySlotIdResponses[keyof PutAppointmentsBookBySlotIdResponses];

export type PutAppointmentsRescheduleBySlotIdData = {
    body?: RescheduleAppointmentData;
    path?: {
        slotId?: number;
    };
    query?: never;
    url: '/appointments/reschedule/{slotId}';
};

export type PutAppointmentsRescheduleBySlotIdErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type PutAppointmentsRescheduleBySlotIdError = PutAppointmentsRescheduleBySlotIdErrors[keyof PutAppointmentsRescheduleBySlotIdErrors];

export type PutAppointmentsRescheduleBySlotIdResponses = {
    /**
     * Reschedule result
     */
    200: BookAppointmentResult;
};

export type PutAppointmentsRescheduleBySlotIdResponse = PutAppointmentsRescheduleBySlotIdResponses[keyof PutAppointmentsRescheduleBySlotIdResponses];

export type PutAppointmentsCancelBySlotIdData = {
    body?: CancelAppointmentData;
    path?: {
        slotId?: number;
    };
    query?: never;
    url: '/appointments/cancel/{slotId}';
};

export type PutAppointmentsCancelBySlotIdErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type PutAppointmentsCancelBySlotIdError = PutAppointmentsCancelBySlotIdErrors[keyof PutAppointmentsCancelBySlotIdErrors];

export type PutAppointmentsCancelBySlotIdResponses = {
    /**
     * Cancellation result
     */
    200: CancelAppointmentResult;
};

export type PutAppointmentsCancelBySlotIdResponse = PutAppointmentsCancelBySlotIdResponses[keyof PutAppointmentsCancelBySlotIdResponses];

export type GetAppointmentsMediumsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/appointments/mediums';
};

export type GetAppointmentsMediumsErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetAppointmentsMediumsError = GetAppointmentsMediumsErrors[keyof GetAppointmentsMediumsErrors];

export type GetAppointmentsMediumsResponses = {
    /**
     * Medium list
     */
    200: Array<MediumItem>;
};

export type GetAppointmentsMediumsResponse = GetAppointmentsMediumsResponses[keyof GetAppointmentsMediumsResponses];

export type GetAppointmentsRoomBySlotIdData = {
    body?: never;
    path?: {
        slotId?: number;
    };
    query?: never;
    url: '/appointments/room/{slotId}';
};

export type GetAppointmentsRoomBySlotIdErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetAppointmentsRoomBySlotIdError = GetAppointmentsRoomBySlotIdErrors[keyof GetAppointmentsRoomBySlotIdErrors];

export type GetAppointmentsRoomBySlotIdResponses = {
    /**
     * Room ID
     */
    200: RoomIdResponse;
};

export type GetAppointmentsRoomBySlotIdResponse = GetAppointmentsRoomBySlotIdResponses[keyof GetAppointmentsRoomBySlotIdResponses];

export type GetPatientsMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/patients/me';
};

export type GetPatientsMeErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not found
     */
    404: Error;
};

export type GetPatientsMeError = GetPatientsMeErrors[keyof GetPatientsMeErrors];

export type GetPatientsMeResponses = {
    /**
     * Patient profile
     */
    200: UserDetails;
};

export type GetPatientsMeResponse = GetPatientsMeResponses[keyof GetPatientsMeResponses];

export type GetPatientsByMobileByMobileData = {
    body?: never;
    path: {
        mobile: string;
    };
    query?: never;
    url: '/patients/by-mobile/{mobile}';
};

export type GetPatientsByMobileByMobileErrors = {
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not found
     */
    404: Error;
};

export type GetPatientsByMobileByMobileError = GetPatientsByMobileByMobileErrors[keyof GetPatientsByMobileByMobileErrors];

export type GetPatientsByMobileByMobileResponses = {
    /**
     * Patient profile
     */
    200: UserDetails;
};

export type GetPatientsByMobileByMobileResponse = GetPatientsByMobileByMobileResponses[keyof GetPatientsByMobileByMobileResponses];

export type GetPatientsByEmailByEmailData = {
    body?: never;
    path: {
        email: string;
    };
    query?: never;
    url: '/patients/by-email/{email}';
};

export type GetPatientsByEmailByEmailErrors = {
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not found
     */
    404: Error;
};

export type GetPatientsByEmailByEmailError = GetPatientsByEmailByEmailErrors[keyof GetPatientsByEmailByEmailErrors];

export type GetPatientsByEmailByEmailResponses = {
    /**
     * Patient profile
     */
    200: UserDetails;
};

export type GetPatientsByEmailByEmailResponse = GetPatientsByEmailByEmailResponses[keyof GetPatientsByEmailByEmailResponses];

export type GetPatientsByLeadIdData = {
    body?: never;
    path?: {
        leadId?: number;
    };
    query?: never;
    url: '/patients/{leadId}';
};

export type GetPatientsByLeadIdErrors = {
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Not found
     */
    404: Error;
};

export type GetPatientsByLeadIdError = GetPatientsByLeadIdErrors[keyof GetPatientsByLeadIdErrors];

export type GetPatientsByLeadIdResponses = {
    /**
     * Patient profile
     */
    200: UserDetails;
};

export type GetPatientsByLeadIdResponse = GetPatientsByLeadIdResponses[keyof GetPatientsByLeadIdResponses];

export type GetPackagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Comma-separated service IDs
         */
        service_ids?: string;
    };
    url: '/packages';
};

export type GetPackagesErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetPackagesError = GetPackagesErrors[keyof GetPackagesErrors];

export type GetPackagesResponses = {
    /**
     * Packages
     */
    200: Array<Package>;
};

export type GetPackagesResponse = GetPackagesResponses[keyof GetPackagesResponses];

export type GetPackagesProductLinesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Comma-separated line IDs
         */
        line_ids?: string;
    };
    url: '/packages/product-lines';
};

export type GetPackagesProductLinesErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetPackagesProductLinesError = GetPackagesProductLinesErrors[keyof GetPackagesProductLinesErrors];

export type GetPackagesProductLinesResponses = {
    /**
     * Product lines
     */
    200: Array<PackageProductLine>;
};

export type GetPackagesProductLinesResponse = GetPackagesProductLinesResponses[keyof GetPackagesProductLinesResponses];

export type GetPackagesProductLinesByPackageIdData = {
    body?: never;
    path?: {
        packageId?: number;
    };
    query?: never;
    url: '/packages/product-lines/{packageId}';
};

export type GetPackagesProductLinesByPackageIdErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetPackagesProductLinesByPackageIdError = GetPackagesProductLinesByPackageIdErrors[keyof GetPackagesProductLinesByPackageIdErrors];

export type GetPackagesProductLinesByPackageIdResponses = {
    /**
     * Product lines
     */
    200: Array<PackageProductLine>;
};

export type GetPackagesProductLinesByPackageIdResponse = GetPackagesProductLinesByPackageIdResponses[keyof GetPackagesProductLinesByPackageIdResponses];

export type GetPackagesManagedData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Required for doctors, auto-resolved for patients
         */
        lead_id?: number;
    };
    url: '/packages/managed';
};

export type GetPackagesManagedErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetPackagesManagedError = GetPackagesManagedErrors[keyof GetPackagesManagedErrors];

export type GetPackagesManagedResponses = {
    /**
     * Managed packages
     */
    200: Array<ManagedPackage>;
};

export type GetPackagesManagedResponse = GetPackagesManagedResponses[keyof GetPackagesManagedResponses];

export type PostPackagesBookData = {
    body?: BookPackageData;
    path?: never;
    query?: never;
    url: '/packages/book';
};

export type PostPackagesBookErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type PostPackagesBookError = PostPackagesBookErrors[keyof PostPackagesBookErrors];

export type PostPackagesBookResponses = {
    /**
     * Booking result
     */
    200: BookPackageResult;
};

export type PostPackagesBookResponse = PostPackagesBookResponses[keyof PostPackagesBookResponses];

export type GetPackagesBookedLineByBookedPackageIdBySequenceNoData = {
    body?: never;
    path?: {
        bookedPackageId?: number;
        sequenceNo?: number;
    };
    query?: never;
    url: '/packages/booked-line/{bookedPackageId}/{sequenceNo}';
};

export type GetPackagesBookedLineByBookedPackageIdBySequenceNoErrors = {
    /**
     * Unauthorized
     */
    401: Error;
    /**
     * Not found
     */
    404: Error;
};

export type GetPackagesBookedLineByBookedPackageIdBySequenceNoError = GetPackagesBookedLineByBookedPackageIdBySequenceNoErrors[keyof GetPackagesBookedLineByBookedPackageIdBySequenceNoErrors];

export type GetPackagesBookedLineByBookedPackageIdBySequenceNoResponses = {
    /**
     * Booked line
     */
    200: BookedPackageProductLine;
};

export type GetPackagesBookedLineByBookedPackageIdBySequenceNoResponse = GetPackagesBookedLineByBookedPackageIdBySequenceNoResponses[keyof GetPackagesBookedLineByBookedPackageIdBySequenceNoResponses];

export type PostPaymentsAppointmentData = {
    body?: AppointmentPaymentParams;
    path?: never;
    query?: never;
    url: '/payments/appointment';
};

export type PostPaymentsAppointmentErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type PostPaymentsAppointmentError = PostPaymentsAppointmentErrors[keyof PostPaymentsAppointmentErrors];

export type PostPaymentsAppointmentResponses = {
    /**
     * Payment init response
     */
    200: PaymentInitResponse;
};

export type PostPaymentsAppointmentResponse = PostPaymentsAppointmentResponses[keyof PostPaymentsAppointmentResponses];

export type PostPaymentsPackageData = {
    body?: PackagePaymentParams;
    path?: never;
    query?: never;
    url: '/payments/package';
};

export type PostPaymentsPackageErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type PostPaymentsPackageError = PostPaymentsPackageErrors[keyof PostPaymentsPackageErrors];

export type PostPaymentsPackageResponses = {
    /**
     * Payment init response
     */
    200: PaymentInitResponse;
};

export type PostPaymentsPackageResponse = PostPaymentsPackageResponses[keyof PostPaymentsPackageResponses];

export type GetConsultationsPsychiatricData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Required for doctors, auto-resolved for patients
         */
        user_id?: number;
        doctor_id?: number;
        limit?: number;
    };
    url: '/consultations/psychiatric';
};

export type GetConsultationsPsychiatricErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetConsultationsPsychiatricError = GetConsultationsPsychiatricErrors[keyof GetConsultationsPsychiatricErrors];

export type GetConsultationsPsychiatricResponses = {
    /**
     * Consultation data
     */
    200: unknown;
};

export type GetConsultationsPsychologistData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Required for doctors, auto-resolved for patients
         */
        user_id?: number;
        doctor_id?: number;
        limit?: number;
    };
    url: '/consultations/psychologist';
};

export type GetConsultationsPsychologistErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetConsultationsPsychologistError = GetConsultationsPsychologistErrors[keyof GetConsultationsPsychologistErrors];

export type GetConsultationsPsychologistResponses = {
    /**
     * Consultation data
     */
    200: unknown;
};

export type GetConsultationsSummaryData = {
    body?: never;
    path?: never;
    query?: {
        user_id?: number;
        include_details?: 'true' | 'false';
    };
    url: '/consultations/summary';
};

export type GetConsultationsSummaryErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetConsultationsSummaryError = GetConsultationsSummaryErrors[keyof GetConsultationsSummaryErrors];

export type GetConsultationsSummaryResponses = {
    /**
     * Summary data
     */
    200: unknown;
};

export type GetConsultationsHistoryData = {
    body?: never;
    path?: never;
    query?: {
        user_id?: number;
        consultation_type?: 'all' | 'psychiatric' | 'psychologist';
        date_from?: string;
        date_to?: string;
        limit?: number;
    };
    url: '/consultations/history';
};

export type GetConsultationsHistoryErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetConsultationsHistoryError = GetConsultationsHistoryErrors[keyof GetConsultationsHistoryErrors];

export type GetConsultationsHistoryResponses = {
    /**
     * History data
     */
    200: unknown;
};

export type GetNotificationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Required for doctors, auto-resolved for patients
         */
        lead_id?: number;
    };
    url: '/notifications';
};

export type GetNotificationsErrors = {
    /**
     * Bad request
     */
    400: Error;
    /**
     * Unauthorized
     */
    401: Error;
};

export type GetNotificationsError = GetNotificationsErrors[keyof GetNotificationsErrors];

export type GetNotificationsResponses = {
    /**
     * Preferences
     */
    200: NotificationPreferences;
};

export type GetNotificationsResponse = GetNotificationsResponses[keyof GetNotificationsResponses];

export type PutNotificationsData = {
    body?: EnableNotificationData;
    path?: never;
    query?: never;
    url: '/notifications';
};

export type PutNotificationsErrors = {
    /**
     * Unauthorized
     */
    401: Error;
};

export type PutNotificationsError = PutNotificationsErrors[keyof PutNotificationsErrors];

export type PutNotificationsResponses = {
    /**
     * Success
     */
    200: Success;
};

export type PutNotificationsResponse = PutNotificationsResponses[keyof PutNotificationsResponses];
