/**
 * FILE: components/shared/ai-pill.tsx
 *
 * PURPOSE:
 *   Reusable AI-generated pill and disclaimer block per the MindTalk design system.
 *   Mandatory on every surface that shows AI-generated content (assessments, chat
 *   summaries, journal reflections, recommendations).
 *
 * LOGIC OVERVIEW:
 *   AIPill — small inline pill: cream bg, peach border, sparkle icon, orange-700 text.
 *   AIDisclaimer — full disclaimer block: pill + non-diagnosis copy with "not a diagnosis"
 *   emphasis in --mt-orange-700. Always shown together on AI summary surfaces.
 *
 * KEY VARIABLES / PROPS / EXPORTS:
 *   AIPill        — pill-only, use in tight spaces (chat bubbles, card corners)
 *   AIDisclaimer  — full block with pill + disclaimer text (assessment reports, summaries)
 *   label         — pill label text (default "AI-generated")
 *   size          — "sm" | "md"
 *
 * DEPENDENCIES:
 *   None (inline SVG sparkle, pure Tailwind + CSS vars)
 *
 * LAST UPDATED: 2026-04-28 — Created as part of Phase 2 design system migration
 */

interface AIPillProps {
  label?: string;
  size?: "sm" | "md";
}

/* Brand sparkle SVG — 4-pointed star, used on AI surfaces per design system */
function Sparkle({ size = 12, color = "#C9531A" }: { size?: number; color?: string }) {
  return (
    <svg width={size} height={size} viewBox="0 0 24 24" fill={color} aria-hidden>
      <path d="M12 2l1.6 4.4L18 8l-4.4 1.6L12 14l-1.6-4.4L6 8l4.4-1.6z" />
      <path d="M19 14l.8 2.2 2.2.8-2.2.8L19 20l-.8-2.2L16 17l2.2-.8z" />
    </svg>
  );
}

export function AIPill({ label = "AI-generated", size = "sm" }: AIPillProps) {
  const isSmall = size === "sm";
  return (
    <span
      className="inline-flex items-center gap-1 rounded-full font-bold"
      style={{
        padding: isSmall ? "5px 10px" : "7px 14px",
        fontSize: isSmall ? 11 : 12,
        background: "#FBF5EF",
        color: "#C9531A",
        border: "1px solid #FFE9D9",
      }}
    >
      <Sparkle size={isSmall ? 11 : 13} />
      {label}
    </span>
  );
}

interface AIDisclaimerProps {
  label?: string;
}

/* Full AI disclaimer block — pill + mandatory non-diagnosis copy.
   Required on every AI-generated summary surface per design system rules. */
export function AIDisclaimer({ label = "AI-generated summary" }: AIDisclaimerProps) {
  return (
    <div
      className="flex flex-col gap-2 rounded-[14px] p-3"
      style={{ background: "#FBF5EF", border: "1px solid #FFE9D9" }}
    >
      <AIPill label={label} size="sm" />
      <p className="text-[12px] leading-relaxed" style={{ color: "#6B7280" }}>
        This summary is generated by AI based on your answers. It is{" "}
        <strong style={{ color: "#C9531A" }}>not a diagnosis</strong> and should be used as a
        reflection aid, not as medical advice. For a clinical assessment, speak with your therapist
        or psychiatrist.
      </p>
    </div>
  );
}
