/**
 * FILE: capacitor.config.ts
 *
 * PURPOSE:
 *   Capacitor configuration for the MindTalk mobile shells (iOS + Android).
 *   The native apps are thin WebView shells pointing at the hosted Next.js
 *   site at https://www.dev-x3.cadabams.com/.
 *
 * LOGIC OVERVIEW:
 *   - `server.url` makes the WebView load the remote Next.js site on every
 *     launch, so JS/UI changes ship by deploying the web app — no store
 *     resubmission needed.
 *   - `webDir: 'out'` is the static-export fallback (used by `cap copy` and
 *     required by the CLI even when `server.url` is set).
 *   - `androidScheme: 'https'` + `cleartext: false` enforce HTTPS on Android.
 *   - `allowNavigation` whitelists the cadabams.com domains so the WebView
 *     can navigate within the app's surface but cannot wander off.
 *   - iOS `limitsNavigationsToAppBoundDomains: true` mirrors that lock-down
 *     and is required for Service Worker / WKWebView features on iOS 14+.
 *
 * KEY VARIABLES / PROPS / EXPORTS:
 *   appId          — com.mindtalk.com (reverse-DNS, must match Play/App Store listings)
 *   appName        — "MindTalk" (display name on the device springboard)
 *   server.url     — Remote URL the WebView loads on launch
 *   webDir         — Static fallback dir produced by `next build` (output: 'export')
 *
 * DEPENDENCIES:
 *   @capacitor/cli, @capacitor/ios, @capacitor/android
 *
 * NATIVE ASSETS:
 *   Icons + splash images are generated by `@capacitor/assets` from the
 *   source PNGs in `assets/icon.png` (1024x1024) and `assets/splash.png`
 *   (2732x2732). Those PNGs are produced by rasterizing the brand SVGs
 *   via `scripts/rasterize-capacitor-assets.mjs`. Run `pnpm assets:gen`
 *   to refresh both the rasterized PNGs and the platform-specific
 *   drawable / AppIcon / Splash.imageset entries.
 *   - Icon background: #D8670E (brand orange — pairs with the white logo)
 *   - Splash background: #fffdf9 (cream, matches the in-app canvas)
 *
 * LAST UPDATED: 2026-05-06 — wired up brand SVG → native icon/splash pipeline
 */
import type { CapacitorConfig } from '@capacitor/cli';

const config: CapacitorConfig = {
  appId: 'com.mindtalk.com',
  appName: 'Cadabams Mindtalk',
  webDir: 'out',
  loggingBehavior: 'none',

  // Cream canvas (--mt-cream-bg from app/globals.css). Painted by the native
  // shell *before* the WebView attaches and during any reflow — without this
  // the user briefly sees white between splash and the remote site.
  backgroundColor: '#fffdf9',

  // Lets the backend distinguish in-app traffic from desktop web in logs / WAF.
  appendUserAgent: 'MindTalkApp',

  server: {
    url: 'https://www.dev-x3.cadabams.com',
    cleartext: false,
    androidScheme: 'https',
    allowNavigation: ['dev-x3.cadabams.com', '*.cadabams.com'],
  },

  ios: {
    contentInset: 'automatic',
    scrollEnabled: true,
    limitsNavigationsToAppBoundDomains: true,
    // Long-press link previews feel web-y; off for native polish.
    allowsLinkPreview: false,
  },

  android: {
    allowMixedContent: false,
    captureInput: false,
    webContentsDebuggingEnabled: false,
  },

  plugins: {
    SplashScreen: {
      launchShowDuration: 1500,
      launchAutoHide: true,
      backgroundColor: '#fffdf9', // --mt-cream-bg
      // Resource names match what `@capacitor/assets` emits into
      // android/app/src/main/res/drawable-* and ios Splash.imageset.
      androidSplashResourceName: 'splash',
      androidScaleType: 'CENTER_CROP',
      splashFullScreen: true,
      splashImmersive: true,
      showSpinner: false,
      useDialog: false,
    },
    StatusBar: {
      // 'LIGHT' = dark text/icons on a light background — matches our cream canvas.
      style: 'LIGHT',
      backgroundColor: '#fffdf9',
      overlaysWebView: false,
    },
    Keyboard: {
      // 'native' lets the OS resize the WebView; the safe-area listener in
      // lib/capacitor/keyboard.ts updates --keyboard-height for layouts that
      // need to react explicitly.
      resize: undefined,
      resizeOnFullScreen: true,
    },
  },
};

export default config;
