// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetApiV1AssessmentsByIdData, GetApiV1AssessmentsByIdErrors, GetApiV1AssessmentsByIdResponses, GetApiV1AssessmentsData, GetApiV1AssessmentsResponses, GetApiV1AudiosByIdData, GetApiV1AudiosByIdErrors, GetApiV1AudiosByIdResponses, GetApiV1AudiosData, GetApiV1AudiosResponses, GetApiV1DebugEnvData, GetApiV1DebugEnvResponses, GetApiV1JournalingByIdData, GetApiV1JournalingByIdErrors, GetApiV1JournalingByIdResponses, GetApiV1JournalingData, GetApiV1JournalingResponses, GetApiV1JournalingSelfByIdData, GetApiV1JournalingSelfByIdErrors, GetApiV1JournalingSelfByIdResponses, GetApiV1JournalingSelfData, GetApiV1JournalingSelfResponses, GetApiV1JournalingSubByIdData, GetApiV1JournalingSubByIdErrors, GetApiV1JournalingSubByIdResponses, GetApiV1JournalingSubData, GetApiV1JournalingSubResponses, GetApiV1JourneysByIdData, GetApiV1JourneysByIdErrors, GetApiV1JourneysByIdResponses, GetApiV1JourneysData, GetApiV1JourneysResponses, GetApiV1MediaData, GetApiV1MediaResponses, GetApiV1MediaUploadUrlData, GetApiV1MediaUploadUrlResponses, GetApiV1MindfulMinutesByIdData, GetApiV1MindfulMinutesByIdErrors, GetApiV1MindfulMinutesByIdResponses, GetApiV1MindfulMinutesData, GetApiV1MindfulMinutesResponses, GetApiV1MindfulMinutesSlugBySlugData, GetApiV1MindfulMinutesSlugBySlugErrors, GetApiV1MindfulMinutesSlugBySlugResponses, GetApiV1MonitoringHealthData, GetApiV1MonitoringHealthResponses, GetApiV1MonitoringOverviewData, GetApiV1MonitoringOverviewResponses, GetApiV1WorksheetsByIdData, GetApiV1WorksheetsByIdErrors, GetApiV1WorksheetsByIdResponses, GetApiV1WorksheetsData, GetApiV1WorksheetsResponses, GetHealthData, GetHealthResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiV1Assessments = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1AssessmentsData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1AssessmentsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/assessments/',
    ...options
});

export const getApiV1AssessmentsById = <ThrowOnError extends boolean = false>(options: Options<GetApiV1AssessmentsByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiV1AssessmentsByIdResponses, GetApiV1AssessmentsByIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/assessments/{id}',
    ...options
});

export const getApiV1Worksheets = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1WorksheetsData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1WorksheetsResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/worksheets/',
    ...options
});

export const getApiV1WorksheetsById = <ThrowOnError extends boolean = false>(options: Options<GetApiV1WorksheetsByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiV1WorksheetsByIdResponses, GetApiV1WorksheetsByIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/worksheets/{id}',
    ...options
});

export const getApiV1Audios = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1AudiosData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1AudiosResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/audios/',
    ...options
});

export const getApiV1AudiosById = <ThrowOnError extends boolean = false>(options: Options<GetApiV1AudiosByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiV1AudiosByIdResponses, GetApiV1AudiosByIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/audios/{id}',
    ...options
});

export const getApiV1MindfulMinutes = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1MindfulMinutesData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1MindfulMinutesResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/mindful-minutes/',
    ...options
});

export const getApiV1MindfulMinutesSlugBySlug = <ThrowOnError extends boolean = false>(options: Options<GetApiV1MindfulMinutesSlugBySlugData, ThrowOnError>) => (options.client ?? client).get<GetApiV1MindfulMinutesSlugBySlugResponses, GetApiV1MindfulMinutesSlugBySlugErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/mindful-minutes/slug/{slug}',
    ...options
});

export const getApiV1MindfulMinutesById = <ThrowOnError extends boolean = false>(options: Options<GetApiV1MindfulMinutesByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiV1MindfulMinutesByIdResponses, GetApiV1MindfulMinutesByIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/mindful-minutes/{id}',
    ...options
});

export const getApiV1MediaUploadUrl = <ThrowOnError extends boolean = false>(options: Options<GetApiV1MediaUploadUrlData, ThrowOnError>) => (options.client ?? client).get<GetApiV1MediaUploadUrlResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/media/upload-url',
    ...options
});

export const getApiV1Media = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1MediaData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1MediaResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/media/',
    ...options
});

export const getApiV1Journaling = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1JournalingData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1JournalingResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/journaling/',
    ...options
});

export const getApiV1JournalingSub = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1JournalingSubData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1JournalingSubResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/journaling/sub',
    ...options
});

export const getApiV1JournalingSubById = <ThrowOnError extends boolean = false>(options: Options<GetApiV1JournalingSubByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiV1JournalingSubByIdResponses, GetApiV1JournalingSubByIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/journaling/sub/{id}',
    ...options
});

export const getApiV1JournalingSelf = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1JournalingSelfData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1JournalingSelfResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/journaling/self',
    ...options
});

export const getApiV1JournalingSelfById = <ThrowOnError extends boolean = false>(options: Options<GetApiV1JournalingSelfByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiV1JournalingSelfByIdResponses, GetApiV1JournalingSelfByIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/journaling/self/{id}',
    ...options
});

export const getApiV1JournalingById = <ThrowOnError extends boolean = false>(options: Options<GetApiV1JournalingByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiV1JournalingByIdResponses, GetApiV1JournalingByIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/journaling/{id}',
    ...options
});

export const getApiV1Journeys = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1JourneysData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1JourneysResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/journeys/',
    ...options
});

export const getApiV1JourneysById = <ThrowOnError extends boolean = false>(options: Options<GetApiV1JourneysByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiV1JourneysByIdResponses, GetApiV1JourneysByIdErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/journeys/{id}',
    ...options
});

export const getApiV1MonitoringHealth = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1MonitoringHealthData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1MonitoringHealthResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/monitoring/health',
    ...options
});

export const getApiV1MonitoringOverview = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1MonitoringOverviewData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1MonitoringOverviewResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/v1/monitoring/overview',
    ...options
});

export const getApiV1DebugEnv = <ThrowOnError extends boolean = false>(options?: Options<GetApiV1DebugEnvData, ThrowOnError>) => (options?.client ?? client).get<GetApiV1DebugEnvResponses, unknown, ThrowOnError>({ url: '/api/v1/debug-env', ...options });

export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>) => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });
