// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

export type GetApiV1AssessmentsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        search?: string;
        status?: 'ALL' | 'DRAFT' | 'PUBLISHED';
        sortBy?: string;
        sortOrder?: 'asc' | 'desc';
    };
    url: '/api/v1/assessments/';
};

export type GetApiV1AssessmentsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1AssessmentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/assessments/{id}';
};

export type GetApiV1AssessmentsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type GetApiV1AssessmentsByIdError = GetApiV1AssessmentsByIdErrors[keyof GetApiV1AssessmentsByIdErrors];

export type GetApiV1AssessmentsByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiV1AssessmentsByIdUnpublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/assessments/{id}/unpublish';
};

export type PostApiV1AssessmentsByIdUnpublishErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type PostApiV1AssessmentsByIdUnpublishError = PostApiV1AssessmentsByIdUnpublishErrors[keyof PostApiV1AssessmentsByIdUnpublishErrors];

export type PostApiV1AssessmentsByIdUnpublishResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1WorksheetsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        search?: string;
        status?: 'DRAFT' | 'PUBLISHED' | 'ALL';
        category?: string;
        grade?: string;
        visibleToAll?: boolean;
        sortBy?: string;
        sortOrder?: 'asc' | 'desc';
    };
    url: '/api/v1/worksheets/';
};

export type GetApiV1WorksheetsResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1WorksheetsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/worksheets/{id}';
};

export type GetApiV1WorksheetsByIdErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type GetApiV1WorksheetsByIdError = GetApiV1WorksheetsByIdErrors[keyof GetApiV1WorksheetsByIdErrors];

export type GetApiV1WorksheetsByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiV1WorksheetsByIdUnpublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/worksheets/{id}/unpublish';
};

export type PostApiV1WorksheetsByIdUnpublishErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type PostApiV1WorksheetsByIdUnpublishError = PostApiV1WorksheetsByIdUnpublishErrors[keyof PostApiV1WorksheetsByIdUnpublishErrors];

export type PostApiV1WorksheetsByIdUnpublishResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1AudiosData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/api/v1/audios/';
};

export type GetApiV1AudiosResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1AudiosByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/audios/{id}';
};

export type GetApiV1AudiosByIdErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type GetApiV1AudiosByIdError = GetApiV1AudiosByIdErrors[keyof GetApiV1AudiosByIdErrors];

export type GetApiV1AudiosByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiV1AudiosByIdUnpublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/audios/{id}/unpublish';
};

export type PostApiV1AudiosByIdUnpublishErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type PostApiV1AudiosByIdUnpublishError = PostApiV1AudiosByIdUnpublishErrors[keyof PostApiV1AudiosByIdUnpublishErrors];

export type PostApiV1AudiosByIdUnpublishResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1MindfulMinutesData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        search?: string;
        status?: 'ALL' | 'DRAFT' | 'PUBLISHED';
    };
    url: '/api/v1/mindful-minutes/';
};

export type GetApiV1MindfulMinutesResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1MindfulMinutesSlugBySlugData = {
    body?: never;
    path: {
        slug: string;
    };
    query?: never;
    url: '/api/v1/mindful-minutes/slug/{slug}';
};

export type GetApiV1MindfulMinutesSlugBySlugErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type GetApiV1MindfulMinutesSlugBySlugError = GetApiV1MindfulMinutesSlugBySlugErrors[keyof GetApiV1MindfulMinutesSlugBySlugErrors];

export type GetApiV1MindfulMinutesSlugBySlugResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1MindfulMinutesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/mindful-minutes/{id}';
};

export type GetApiV1MindfulMinutesByIdErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type GetApiV1MindfulMinutesByIdError = GetApiV1MindfulMinutesByIdErrors[keyof GetApiV1MindfulMinutesByIdErrors];

export type GetApiV1MindfulMinutesByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiV1MindfulMinutesByIdUnpublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/mindful-minutes/{id}/unpublish';
};

export type PostApiV1MindfulMinutesByIdUnpublishErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type PostApiV1MindfulMinutesByIdUnpublishError = PostApiV1MindfulMinutesByIdUnpublishErrors[keyof PostApiV1MindfulMinutesByIdUnpublishErrors];

export type PostApiV1MindfulMinutesByIdUnpublishResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1MediaUploadUrlData = {
    body?: never;
    path?: never;
    query: {
        fileName: string;
        mimeType: string;
    };
    url: '/api/v1/media/upload-url';
};

export type GetApiV1MediaUploadUrlResponses = {
    /**
     * Default Response
     */
    200: {
        success: true;
        data: {
            uploadUrl: string;
            key: string;
            fileUrl: string;
        };
    };
};

export type GetApiV1MediaUploadUrlResponse = GetApiV1MediaUploadUrlResponses[keyof GetApiV1MediaUploadUrlResponses];

export type GetApiV1MediaData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        search?: string;
        type?: 'all' | 'image' | 'audio' | 'video';
    };
    url: '/api/v1/media/';
};

export type GetApiV1MediaResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1JournalingData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/api/v1/journaling/';
};

export type GetApiV1JournalingResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1JournalingSubData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        search?: string;
        status?: 'DRAFT' | 'PUBLISHED' | 'ALL';
    };
    url: '/api/v1/journaling/sub';
};

export type GetApiV1JournalingSubResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1JournalingSubByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/journaling/sub/{id}';
};

export type GetApiV1JournalingSubByIdErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type GetApiV1JournalingSubByIdError = GetApiV1JournalingSubByIdErrors[keyof GetApiV1JournalingSubByIdErrors];

export type GetApiV1JournalingSubByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiV1JournalingSubByIdUnpublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/journaling/sub/{id}/unpublish';
};

export type PostApiV1JournalingSubByIdUnpublishErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type PostApiV1JournalingSubByIdUnpublishError = PostApiV1JournalingSubByIdUnpublishErrors[keyof PostApiV1JournalingSubByIdUnpublishErrors];

export type PostApiV1JournalingSubByIdUnpublishResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1JournalingSelfData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/api/v1/journaling/self';
};

export type GetApiV1JournalingSelfResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1JournalingSelfByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/journaling/self/{id}';
};

export type GetApiV1JournalingSelfByIdErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type GetApiV1JournalingSelfByIdError = GetApiV1JournalingSelfByIdErrors[keyof GetApiV1JournalingSelfByIdErrors];

export type GetApiV1JournalingSelfByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1JournalingByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/journaling/{id}';
};

export type GetApiV1JournalingByIdErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type GetApiV1JournalingByIdError = GetApiV1JournalingByIdErrors[keyof GetApiV1JournalingByIdErrors];

export type GetApiV1JournalingByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiV1JournalingByIdUnpublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/journaling/{id}/unpublish';
};

export type PostApiV1JournalingByIdUnpublishErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type PostApiV1JournalingByIdUnpublishError = PostApiV1JournalingByIdUnpublishErrors[keyof PostApiV1JournalingByIdUnpublishErrors];

export type PostApiV1JournalingByIdUnpublishResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1JourneysData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
        search?: string;
        status?: 'ALL' | 'DRAFT' | 'PUBLISHED';
        sortBy?: 'name' | 'status' | 'createdAt' | 'updatedAt' | 'isPremium' | 'documentId';
        sortOrder?: 'asc' | 'desc';
    };
    url: '/api/v1/journeys/';
};

export type GetApiV1JourneysResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1JourneysByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/journeys/{id}';
};

export type GetApiV1JourneysByIdErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type GetApiV1JourneysByIdError = GetApiV1JourneysByIdErrors[keyof GetApiV1JourneysByIdErrors];

export type GetApiV1JourneysByIdResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type PostApiV1JourneysByIdUnpublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/api/v1/journeys/{id}/unpublish';
};

export type PostApiV1JourneysByIdUnpublishErrors = {
    /**
     * Default Response
     */
    404: {
        message: string;
    };
};

export type PostApiV1JourneysByIdUnpublishError = PostApiV1JourneysByIdUnpublishErrors[keyof PostApiV1JourneysByIdUnpublishErrors];

export type PostApiV1JourneysByIdUnpublishResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1MonitoringHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/monitoring/health';
};

export type GetApiV1MonitoringHealthResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1MonitoringOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/monitoring/overview';
};

export type GetApiV1MonitoringOverviewResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetApiV1DebugEnvData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/debug-env';
};

export type GetApiV1DebugEnvResponses = {
    /**
     * Default Response
     */
    200: unknown;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Default Response
     */
    200: unknown;
};
