/**
 * FILE: lib/config.ts
 *
 * PURPOSE:
 *   Exports the shared chat loading messages array for use across the chat feature.
 *   Mastra config values are now accessed directly via CONFIG from config/env.ts.
 *
 * LOGIC OVERVIEW:
 *   CHAT_REMAINING_MESSAGES is a static array of empathetic loading strings
 *   shown in the chat UI while awaiting AI replies.
 *
 * KEY VARIABLES / PROPS / EXPORTS:
 *   CHAT_REMAINING_MESSAGES — Array of empathetic loading strings for the chat UI
 *
 * DEPENDENCIES:
 *   None
 *
 * LAST UPDATED: 2026-04-17 — removed MASTRA_* re-exports; consumers now use CONFIG directly
 */

export const CHAT_REMAINING_MESSAGES = [
  // Listening & understanding
  "Taking a moment to understand",
  "Carefully considering your situation",
  "Listening closely to what you've shared",
  "Considering every part of what you said",
  "Reading between the lines to understand you better",
  "Holding space for what you've expressed",
  "Sitting with your words for a moment",
  "Letting what you shared settle in",
  "Taking in everything you've said",
  "Paying close attention to your feelings",
  "Absorbing what you've told me",
  "Hearing you — every word matters",
  "Making sure I truly understand you",
  "Tuning in to what you need right now",
  "Giving your words the weight they deserve",
  "Noticing the details in what you shared",
  "Keeping your feelings at the centre of this",
  "Really taking in what you've expressed",
  "Reflecting on what you've opened up about",
  "Staying present with your words",

  // Care & sensitivity
  "Giving this the care it deserves",
  "Approaching this with the sensitivity it deserves",
  "Choosing words carefully so they feel right",
  "Making sure my response is helpful and safe",
  "Handling this gently — it matters",
  "Being mindful of how this lands for you",
  "Treating your experience with respect",
  "Responding with the warmth this deserves",
  "Making sure this feels supportive, not rushed",
  "Crafting a response that honours your feelings",
  "Being gentle with what you've shared",
  "Holding your experience with care",
  "Making sure nothing I say feels dismissive",
  "Being thoughtful about every word",
  "Responding with the kindness you deserve",
  "Keeping compassion at the heart of this",
  "Making sure this response feels safe for you",
  "Being careful not to overlook what matters to you",
  "Putting your wellbeing first in my response",
  "Wrapping this answer in care",

  // Effort & thoroughness
  "Reviewing what matters most here",
  "Making sure I get this right for you",
  "Thinking through this thoughtfully",
  "Working through this with care",
  "Being thorough so nothing important is missed",
  "Pausing to give this the full attention it needs",
  "Considering how best to respond with care",
  "Making sure this response feels right for you",
  "Wanting to get this just right for you",
  "Taking the time this deserves",
  "Not rushing — you deserve a thoughtful reply",
  "Going through this step by step for you",
  "Double-checking that my response truly helps",
  "Making sure every part of my answer matters",
  "Putting thought into what will help most",
  "Weighing the best way to support you here",
  "Considering different angles to help you best",
  "Looking at this from your perspective",
  "Thinking about what would feel most useful",
  "Exploring the most supportive way to respond",

  // Time & patience
  "Taking time to find the best response",
  "Taking a little more time to do this well",
  "Almost there — this deserves a thorough answer",
  "Still with you, just making sure this is right",
  "Still here — taking the time to get this right",
  "Just a moment more — I want this to be helpful",
  "Spending a little extra time on this for you",
  "Nearly ready — making final adjustments",
  "Giving this one more careful look",
  "Polishing my thoughts so they land well",
  "Taking a breath and making sure this is right",
  "A few more seconds — this matters too much to rush",
  "Worth the wait — your feelings deserve that",
  "Finalising something that feels right",
  "One more moment of careful thought",
  "Just making sure everything feels complete",
  "Putting the finishing touches on my response",
  "Almost ready — wanted to be extra careful",
  "Wrapping up my thoughts with care",
  "Nearly there — your patience means a lot",

  // You-centred & affirming
  "Reflecting on what would truly help here",
  "Thinking about the best way to support you",
  "Your feelings are at the centre of my thoughts",
  "Centering my response around what you need",
  "Focusing entirely on what serves you best",
  "Keeping you at the heart of this",
  "This is all about you right now",
  "You have my full attention",
  "Everything I'm doing is for your benefit",
  "Your experience is guiding my response",
  "Building a response around your needs",
  "Tailoring my thoughts to your situation",
  "Putting your needs first",
  "Shaping this to fit what you're going through",
  "Making this personal to your experience",
  "You're the priority here",
  "Focusing on what will help you most",
  "Orienting my response to your world",
  "Anchoring this in what you've shared",
  "Designing my response with you in mind",

  // Warmth & presence
  "I'm right here with you",
  "You're not alone in this",
  "Staying close while I think",
  "Present and thinking of you",
  "Right here — not going anywhere",
  "Holding steady while I gather my thoughts",
  "With you every step of the way",
  "Your courage in sharing doesn't go unnoticed",
  "Grateful you trusted me with this",
  "What you shared takes strength",
  "I'm glad you felt safe enough to share",
  "Thank you for letting me in",
  "Your honesty means a lot",
  "It takes courage to open up like this",
  "I appreciate you sharing this with me",
  "This space is yours — take your time too",
  "I'm here for you, fully",
  "You matter, and so does what you've said",
  "Everything you feel is valid",
  "I see you, and I hear you",

  // Safety & reassurance
  "Making sure this space stays safe for you",
  "Keeping this conversation a comfort zone",
  "Your privacy and safety come first",
  "Building a response you can trust",
  "Making sure you feel supported, not judged",
  "Creating a thoughtful and safe reply",
  "This is a judgement-free space",
  "You can share as much or as little as you want",
  "There's no wrong way to feel",
  "Whatever you're feeling is okay",
  "No pressure — we go at your pace",
  "This conversation is yours to steer",
  "I'm here to support, not to push",
  "Your comfort is what matters most",
  "Take all the time you need",
  "We can explore this at whatever pace feels right",
  "There's no rush on your end",
  "I'll follow your lead",
  "This is a safe place to be yourself",
  "You set the pace — I'm here to match it",

  // Empathy & validation
  "What you're going through matters",
  "Your experience is important",
  "Acknowledging how you feel right now",
  "Your emotions make complete sense",
  "It's okay to feel the way you do",
  "There's strength in what you're feeling",
  "Your feelings tell an important story",
  "Honouring where you are right now",
  "Meeting you exactly where you are",
  "Recognising the weight of what you carry",
  "You don't have to have it all figured out",
  "It's okay not to be okay",
  "What you feel is real and it matters",
  "Your struggles don't define you — but they do matter",
  "Acknowledging your courage in being here",
  "Every feeling you have is welcome here",
  "You deserve to be heard — fully",
  "Your voice matters in this conversation",
  "Validating everything you've expressed",
  "Nothing you've said is too much",

  // Thoughtful process
  "Connecting the dots in what you've shared",
  "Weaving together a thoughtful response",
  "Thinking about what resonates most for you",
  "Finding the right words — they matter here",
  "Considering the nuances of your situation",
  "Reflecting on the bigger picture of what you shared",
  "Thinking about both what you said and what you might need",
  "Processing this with empathy and care",
  "Bringing together understanding and support",
  "Balancing honesty with gentleness",
  "Making sure my response adds something meaningful",
  "Looking for the most compassionate path forward",
  "Thinking about what would comfort you right now",
  "Considering what kind of support fits best",
  "Exploring the most helpful way to frame this",
  "Searching for words that match your experience",
  "Aligning my response with your needs",
  "Making sure this feels like a real conversation",
  "Putting care into every sentence",
  "Finding the balance between thoughtful and warm",
];
